apiVersion: batch/v1
kind: Job
metadata:
  name: users-migration-job
spec:
  template:
    spec:
      containers:
        - name: wait-for-mysql
          image: busybox
          command: ["sh", "-c", "until nc -z mysql-service 3306; do sleep 1; done;"]
        - name: alembic-migration-container
          image: nahid111/py-micro-users
          envFrom:
            - secretRef:
                name: secrets
          command: [ "sh", "-c", "alembic upgrade head" ]
      restartPolicy: Never
  backoffLimit: 8
