apiVersion: batch/v1
kind: Job
metadata:
  name: users-migration-job
  namespace: ns-py-micro
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-service -p 5432; do
                echo "waiting for postgres"
                sleep 2
              done
      containers:
        - name: alembic-migration-container
          image: nahid111/py-micro-users
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: secrets
          command: [ "sh", "-c", "alembic upgrade head" ]
      restartPolicy: Never
  backoffLimit: 8
